name: Release on Merge to Master

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  build-and-deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          version: 9
      - name: Run Pnpm
        run: pnpm install --no-frozen-lockfile
      - name: Build
        run: pnpm build
      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@master
        with:
          # This expects you to have a script called release which does a build for your packages and calls changeset publish
          publish: pnpm changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
